Prem-gateway installation
premAI-io/prem-box pull request #18
Opened 2023-09-18 10:15 UTC by sekulicd

This adds neccessery docker-compose files and updates existing scripts in order to install prem-gateway with prem-app and prem-daemon if user decides to.

This closes #17 

@tiero @filopedraz please review.

Note that this is dependent on [this](https://github.com/premAI-io/prem-gateway/pull/5)

2023-09-18 10:43 UTC, filopedraz requested changes

2023-09-18 10:43 UTC, filopedraz commented on docker-compose.premg.yml
> +      - ./traefik/letsencrypt:/letsencrypt
Instead of folders, I would prefer if we use docker volumes in order to be able to interact with them through docker cli. e.g., `docker volume rm x`

2023-09-18 10:43 UTC, filopedraz commented on docker-compose.premg.yml
> +    volumes:
Same for pg container. I would prefer volumes instead of folders.

2023-09-18 11:12 UTC, sekulicd commented on docker-compose.premg.yml
> +    volumes:
Agree.

2023-09-18 11:14 UTC, sekulicd commented on docker-compose.premg.yml
> +      - ./traefik/letsencrypt:/letsencrypt
Considering ./traefik/letsencrypt contains acme.json file we would need manually to insert file in volume right using Docker CLI? @filopedraz

2023-09-18 11:33 UTC, filopedraz commented on docker-compose.premg.yml
> +      - ./traefik/letsencrypt:/letsencrypt
Why manually? Traefik I believe already appends the files in the correct way. From our side, it's just simpler to handle docker volumes than folders, but on traefik docker container side nothing changes :) 

Maybe I didn't understand the question

2023-09-18 14:16 UTC, sekulicd commented on docker-compose.premg.yml
> +      - ./traefik/letsencrypt:/letsencrypt
Done

2023-09-18 14:16 UTC, sekulicd commented on docker-compose.premg.yml
> +    volumes:
Done

2023-09-18 15:11 UTC, filopedraz approved these changes

2023-09-18 15:12 UTC, filopedraz commented
@tiero when you want you can merge and then we need to bump the new versions

2023-09-21 12:28 UTC, sekulicd commented
After I manage to publish prem-gateway's docker images to ghrc i tested script and added few fixes.
I was not able to pull docker images without removing version in [here](https://github.com/sekulicd/prem-box/blob/ffcd1c34031224722c042cb4919e5a17c69a0f9c/install.sh#L256), to me it looks like version is not needed at all and that we need to follow <image>@<digest> format.
Also note that i now prompt user for dnsd postgres password, not sure if this is best ux.

@tiero @filopedraz let me know what u think.

2023-09-21 14:46 UTC, tiero commented
> Also note that i now prompt user for dnsd postgres password, not sure if this is best ux.

What about creating one by default? eventually, the daemon can expose an API to check and update the database password?

2023-09-22 10:11 UTC, sekulicd commented
> > Also note that i now prompt user for dnsd postgres password, not sure if this is best ux.
> 
> What about creating one by default? eventually, the daemon can expose an API to check and update the database password?

I changed script to gen pass for dnsd service.
Should i now do as follows:
Store original pass in db where table pass will have columns value, is_hash and when dnsd is started i would store original pass and set is_hash to false.
User would be able to change pass in a way that first he would not need to provide old pass but after initial change he would and pass would be stored as hash.
Other option is to show pass to the user when install script finishes and ask user for that pass if he wants to change it in settings screen.
WDYT @tiero ?

2023-09-22 12:01 UTC, sekulicd commented
> > > Also note that i now prompt user for dnsd postgres password, not sure if this is best ux.
> > 
> > 
> > What about creating one by default? eventually, the daemon can expose an API to check and update the database password?
> 
> I changed script to gen pass for dnsd service. Should i now do as follows: Store original pass in db where table pass will have columns value, is_hash and when dnsd is started i would store original pass and set is_hash to false. User would be able to change pass in a way that first he would not need to provide old pass but after initial change he would and pass would be stored as hash. Other option is to show pass to the user when install script finishes and ask user for that pass if he wants to change it in settings screen. WDYT @tiero ?

When i think twice i am wondering why should we let user change db pass? @tiero

2023-09-23 14:47 UTC, tiero commented
> When i think twice i am wondering why should we let user change db pass

That is a good point also: in the end if is randomly generated INSIDE the infrastructure of the user, he can always log in manually to fetch it if he has an issue. Still we need to save it somewhere to be able to source via the ENV?

2023-09-25 16:52 UTC, sekulicd commented
> > When i think twice i am wondering why should we let user change db pass
> 
> That is a good point also: in the end if is randomly generated INSIDE the infrastructure of the user, he can always log in manually to fetch it if he has an issue. Still we need to save it somewhere to be able to source via the ENV?

I added basic auth into installation, i generate user/pass randomly for basic auth, store it in file and show it to user. @tiero

2023-09-27 01:52 UTC, tiero commented on docker-compose.premapp.premd.yml
> +      - VITE_IS_PACKAGED=true
Is this still needed when proxy enabled 
?

2023-09-27 01:52 UTC, tiero commented on install.sh
> +versions_json=$(curl --silent htt ps://raw.githubusercontent.com/premAI-io/prem-box/main/versions.json)
White space?

2023-09-27 01:52 UTC, tiero commented on install.sh
> +    read -p "nvidia-smi is not available. Do you want to install prem-gateway with prem-app and prem-daemon? [y/N]: " choice
Why we should only ask to install only if we don't have a NVIDIA GPU?

2023-09-27 11:15 UTC, sekulicd commented on docker-compose.premapp.premd.yml
> +      - VITE_IS_PACKAGED=true
wow, fixed

2023-09-27 11:15 UTC, sekulicd commented on install.sh
> +versions_json=$(curl --silent htt ps://raw.githubusercontent.com/premAI-io/prem-box/main/versions.json)
wow, fixed

2023-09-27 11:15 UTC, sekulicd commented on install.sh
> +    read -p "nvidia-smi is not available. Do you want to install prem-gateway with prem-app and prem-daemon? [y/N]: " choice
Done

2023-09-27 11:16 UTC, sekulicd commented on docker-compose.premapp.premd.yml
> +      - VITE_IS_PACKAGED=true
i think so, since there can be scenario where premapp is not installed with 'backend' on same host.

2023-09-28 16:57 UTC, tiero commented
resolve conflicts @sekulicd

2023-09-28 17:59 UTC, sekulicd commented
> resolve conflicts @sekulicd

Done

2023-09-29 07:24 UTC, filopedraz commented
As soon as we merge this PR, I'll test it on Paperspace. @tiero I want to move the [demo](https://app.prem.ninja/) to a GPU server before the conference.

2023-09-29 13:57 UTC, sekulicd commented on README.md
> +When a new version (tag) of [Prem Gatewat](https://github.com/premAI-io/prem-gateway), [Prem App](https://github.com/premAI-io/prem-app) or   [Prem Daemon](https://github.com/premAI-io/prem-daemon) h
Done

2023-10-02 14:55 UTC, tiero commented
Testing on Ubuntu 20

```sh
wget -q https://raw.githubusercontent.com/sekulicd/prem-box/prem-gateway-installation/install.sh -O install.sh; sudo bash ./install.sh

🤖 Welcome to Prem installer!
This script will install all requirements to run Prem

252 packages can be upgraded. Run 'apt list --upgradable' to see them.
jq is already the newest version (1.6-1ubuntu0.20.04.1).
The following packages were automatically installed and are no longer required:
  docker-scan-plugin gir1.2-goa-1.0 libfwupdplugin1 libxmlb1 linux-headers-5.4.0-124
  linux-headers-5.4.0-124-generic linux-image-5.4.0-124-generic linux-modules-5.4.0-124-generic
  linux-modules-extra-5.4.0-124-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  curl libcurl4
2 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.
Need to get 396 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 252991 files and directories currently installed.)
Preparing to unpack .../curl_7.68.0-1ubuntu2.19_amd64.deb ...
Unpacking curl (7.68.0-1ubuntu2.19) over (7.68.0-1ubuntu2.18) ...
Preparing to unpack .../libcurl4_7.68.0-1ubuntu2.19_amd64.deb ...
Unpacking libcurl4:amd64 (7.68.0-1ubuntu2.19) over (7.68.0-1ubuntu2.18) ...
Setting up libcurl4:amd64 (7.68.0-1ubuntu2.19) ...
Setting up curl (7.68.0-1ubuntu2.19) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Check Docker Compose standalone CLI version
Installing Docker Compose.
👷‍♂️ Installing Prem
⬇️ Pulling latest version...
App Version: v0.0.30
App Image: ghcr.io/premai-io/prem-app
App Digest: sha256:8079023f675197dc0ff50cf4fcb19e6e654a6bccbcebc2aca7f1c0457649358d
🏁 Starting Prem...
Do you want to install prem-gateway with prem-app and prem-daemon? [y/N]: y
Installing prem-gateway, prem-app, and prem-daemon...
**parsing /root/prem/docker-compose.premg.yml: Non-string key at top level: 404**
```

2023-10-02 15:05 UTC, tiero approved these changes

2023-10-02 15:05 UTC, merged